---
apiVersion: v1
kind: ConfigMap
metadata:
  name: thanos-proxy-ns-config
data:
  ns-config.yaml: |
    type: ns-list
    paras:
      namespaces:
      - "namespace-1"
      - "namespace-2"
      - "project-.+"
---
apiVersion: v1
kind: Secret
metadata:
  name: thanos-proxy-token
type: Opaque
data:
  token: <insert base64 token>
---
apiVersion: v1
kind: Service
metadata:
  name: thanos-proxy
spec:
  ports:
  - name: thanos-proxy
    port: 9096
    protocol: TCP
    targetPort: 9096
  selector:
    name: thanos-proxy
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: thanos-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      name: thanos-proxy
  template:
    metadata:
      labels:
        name: thanos-proxy
    spec:
      containers:
        - name: thanos-proxy
          image: registry/image:tag
          command:
          - grafana-ocpthanos-proxy
          - --listen-address=0.0.0.0:9096
          imagePullPolicy: Always
          volumeMounts:
          - mountPath: /etc/conf
            name: ns-config
          - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
            name: token
      volumes:
      - configMap:
          name: thanos-proxy-ns-config
          items:
          - key: ns-config.yaml
            path: ns-config.yaml
        name: ns-config
      - secret:
          secretName: thanos-proxy-token
        name: token